apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: crud-app
  labels:
    app: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: michael1723/crud-backend:latest # sera remplacé par sed dans le workflow
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
          # ==================================
          # STARTUP PROBE (évite crash prématuré)
          # ==================================
          startupProbe:
            httpGet:
              path: /health
              port: 5000
            failureThreshold: 30  # attend jusqu’à 5 minutes si nécessaire
            periodSeconds: 10
          # ==================================
          # READINESS PROBE
          # ==================================
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 5
          # ==================================
          # LIVENESS PROBE
          # ==================================
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 20
            failureThreshold: 3
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
      restartPolicy: Always
